variables:
  headers:
    none: ''
    plaintext: '--header "Accept: text/plain,text/html;q=0.9,application/xhtml+xml;q=0.9,application/xml;q=0.8,*/*;q=0.7" --header "Connection: keep-alive"'
    html: '--header "Accept: text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8" --header "Connection: keep-alive"'
    json: '--header "Accept: application/json,text/html;q=0.9,application/xhtml+xml;q=0.9,application/xml;q=0.8,*/*;q=0.7" --header "Connection: keep-alive"'
    connectionclose: '--header "Connection: close"'
    presetHeaders: none

jobs:
  wrk:
    source:
      repository: https://github.com/dotnet/crank.git
      branchOrCommit: master
      project: src/Microsoft.Crank.Jobs.Wrk/Microsoft.Crank.Jobs.Wrk.csproj
    isConsoleApp: true
    waitForExit: true
    variables:
      connections: 256  # total number of HTTP connections to keep open with each thread handling N = connections/threads
      duration: 15 # duration in seconds
      warmup: 15 # warmup in seconds
      threads: 32 # total number of threads to use
      pipeline: 1
      script: '' # path or url of a LUA script, e.g., https://raw.githubusercontent.com/wg/wrk/master/scripts/post.lua
      scriptArguments: '' # arguments passed to the script, e.g., 16
      serverScheme: http
      serverAddress: localhost
      serverPort: 5000
      serverPath: /
    requiredVariables:
      serverUri: http://10.0.0.102
      serverPort: 5000
    arguments: "-c {{connections}} {% if serverUri == blank or serverUri == empty %} {{serverScheme}}://{{serverAddress}}:{{serverPort}}{{path}} {% else %} {{serverUri}}:{{serverPort}}{{path}} {% endif %} --latency -d {{duration}}s -w {{warmup}}s -t {{threads}} {{headers[presetHeaders]}} {% if pipeline > 1 %} -s scripts/pipeline.lua -- {{ pipeline }} {% elsif script != empty or script != blank  %} -s {{script}} -- {{scriptArguments}} {% endif %}"
