jobs:
  dotnet:
    source:
      repository: https://github.com/dotnet/performance
      branchOrCommit: main
      project: src/benchmarks/micro/MicroBenchmarks.csproj
    variables:
      filterArg: "*"
      jobArg: short
    arguments: --job {{jobArg}} --filter {{filterArg}} --memory
    framework: netcoreapp3.1
    options:
      benchmarkDotNet: true
    
scenarios:

  Linq:
    application:
      job: dotnet
      variables:
        filterArg: "*LinqBenchmarks*"

  Sockets:
    application:
      job: dotnet
      variables:
        filterArg: "*SocketSendReceivePerfTest*"

profiles:
  local:
    jobs: 
      application:
        endpoints: 
          - http://localhost:5010
