# multi-line script used to build the project
builds:
    kestrel: 
        script: |
            # echo FAKE KESTREL BUILD
            ./src/Servers/Kestrel/build.cmd -c release -NoBuildNative -NoBuildJava  -NoBuildNodeJs
        arguments:
            --application.options.outputFiles ./artifacts/bin/Microsoft.AspNetCore.Server.Kestrel/release/net7.0/
    mvc: 
        script: |
            echo FAKE MVC BUILD
            # ./src/Servers/Kestrel/build.sh -c release
        arguments: 
            --application.options.outputFiles ./artifacts/bin/Microsoft.AspNetCore.MVC/release/net7.0/

# default arguments that are always used on crank commands
# defaults: --config https://github.com/aspnet/Benchmarks/blob/main/build/azure.profile.yml?raw=true --relay AZURE_RELAY --application.framework net7.0 --application.options.outputFiles ./artifacts/bin/Microsoft.AspNetCore.Server.Kestrel/release/net7.0/
defaults: --variable duration=2 --variable warmup=0 --config https://github.com/aspnet/Benchmarks/blob/main/build/azure.profile.yml?raw=true --application.framework net7.0 # --application.options.outputFiles ./artifacts/bin/Microsoft.AspNetCore.Server.Kestrel/release/net7.0/

# the first value is the default if none is specified
profiles:
    aspnet-perf-lin:
        description: INTEL/Linux 12 Cores
        arguments: --profile aspnet-perf-lin

    aspnet-perf-win:
        description: INTEL/Windows 12 Cores
        arguments: --profile aspnet-perf-win-relay

benchmarks:
    plaintext:
      description: TechEmpower Plaintext Scenario - ASP.NET Middleware
      arguments: --config https://raw.githubusercontent.com/aspnet/Benchmarks/main/scenarios/plaintext.benchmarks.yml --scenario plaintext

    json:
      description: TechEmpower JSON Scenario - ASP.NET Middleware
      arguments: --config https://raw.githubusercontent.com/aspnet/Benchmarks/main/scenarios/json.benchmarks.yml --scenario json
