variables:
  headers:
    none: ''
    grpc: '--header "content-type: application/grpc" --header "TE: trailers"'
    grpcDeadline: '--header "content-type: application/grpc" --header "TE: trailers" --header "grpc-timeout: 100S"'
  presetHeaders: none

jobs:
  h2LoadClient:
    source:
      repository: https://github.com/dotnet/crank.git
      branchOrCommit: main
      project: src/Microsoft.Crank.Jobs.H2Load/Microsoft.Crank.Jobs.H2Load.csproj
      sourceKey: h2load
      noBuild: true
    readyStateText: H2Load Client
    waitForExit: true
    variables:
      threads: 1
      streams: 1
      connections: 1
      requests: 0
      duration: 15
      warmup: 5
      protocol: h2c
      body: ''
      bodyFile: '' # url for a file to use as the body content
      presetHeaders: none
      serverScheme: http
      serverAddress: localhost      
      serverPort: 5000
    arguments: "-c {{connections}} -t {{threads}} -m {{streams}} -d {{duration}} -w {{warmup}} -n {{requests}} -u {% if serverUri == blank %} {{serverScheme}}://{{serverAddress}}:{{serverPort}}{{path}} {% else %} {{serverUri}}:{{serverPort}}{{path}} {% endif %} -p {{ protocol }} {{headers[presetHeaders]}} {% if body != blank %} --body {{ body }} {% endif %} {% if bodyFile %} --bodyFile {{ bodyFile }} {% endif %}"
    options:
      requiredOperatingSystem: linux
